[providers]
python = "3.10"
nodejs = "18"

[phases.build]
cmds = [
    "cd vanachitra-prototype && npm install && npm run build",
    "mkdir -p fradss/react_build",
    "cp -r vanachitra-prototype/build/* fradss/react_build/"
]

[start]
cmd = "cd fradss && python app.py"
